### ISSUE TITLE
Exclude Function

### ISSUE THREAD

**Issue by dillongaf** [mjfwalsh/adb-sync#1]
How would I go about excluding the `/sdcard/Android/` directory?

I've tried `--exclude '/sdcard/Android/'` and `--exclude 'Android/'`

This is all I'm missing from google's adb-sync, it would be great to have :)

**Comment by mjfwalsh** [comment]
As it stands, the examples you give will never match anything as excludes are only matched against filenames and not paths. `--exclude Android` would work but with the drawback that any other directories and files called Android would also be excluded, not just the one at /sdcard/Android

Still what you're looking for makes sense, so I'll have a go adding that feature when I get the time.

**Comment by mjfwalsh** [comment]
Fixed in commit d0f0e09
