### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by dillongaf** [mjfwalsh/adb-sync#2]
What am I doing wrong here? 

> ./adb-sync -rcdmn --exclude-path /sdcard/Android/ /sdcard/ /run/media/dilligaf/Vault/Pixel6

> Dry run mode
Indexing files
find: exec stat: Argument list too long
find: exec stat: Argument list too long
Failed to fully index Android directory
Aborting sync...

Thanks for adding the exclude-path flag btw

**Comment by mjfwalsh** [comment]
No trouble.

What toybox version are you running?

Try the following commands
```
adb shell toybox --version
adb shell stat --help
```
and then post the output here.

**Comment by dillongaf** [comment]
```
adb shell toybox --version
toybox 0.8.4-android
```

```
adb shell stat --help
Toybox 0.8.4-android multicall binary: https://landley.net/toybox (see toybox --help)

usage: stat [-tfL] [-c FORMAT] FILE...

Display status of files or filesystems.

-c	Output specified FORMAT string instead of default
-f	Display filesystem status instead of file status
-L	Follow symlinks
-t	terse (-c "%n %s %b %f %u %g %D %i %h %t %T %X %Y %Z %o")
	      (with -f = -c "%n %i %l %t %s %S %b %f %a %c %d")

The valid format escape sequences for files:
%a  Access bits (octal) |%A  Access bits (flags)|%b  Size/512
%B  Bytes per %b (512)  |%C  Security context   |%d  Device ID (dec)
%D  Device ID (hex)     |%f  All mode bits (hex)|%F  File type
%g  Group ID            |%G  Group name         |%h  Hard links
%i  Inode               |%m  Mount point        |%n  Filename
%N  Long filename       |%o  I/O block size     |%s  Size (bytes)
%t  Devtype major (hex) |%T  Devtype minor (hex)|%u  User ID
%U  User name           |%x  Access time        |%X  Access unix time
%y  Modification time   |%Y  Mod unix time      |%z  Creation time
%Z  Creation unix time

The valid format escape sequences for filesystems:
%a  Available blocks    |%b  Total blocks       |%c  Total inodes
%d  Free inodes         |%f  Free blocks        |%i  File system ID
%l  Max filename length |%n  File name          |%s  Best transfer size
%S  Actual block size   |%t  FS type (hex)      |%T  FS type (driver name)
```

**Comment by mjfwalsh** [comment]
Sorry for the terrible delay in responding. Your setup looks good. You could try using the following version of adb-sync, it might get around the problem.

https://gist.github.com/mjfwalsh/9e46516e3447c950d127e4b80de30e66

**Comment by dillongaf** [comment]
Still no luck, looks like progress though. 

Here's the output now;
`./adb-sync -rcdmn --exclude-path /sdcard/Android/ /sdcard/ /run/media/dilligaf/Vault/PixelTest`

> Dry run mode
Indexing files
find: ./Android/data/org.videolan.vlc/files/medialib: Permission denied
Failed to fully index Android directory
Aborting sync...

Not sure if it's relevant, but my PC is running Linux and my phone is rooted.
Maybe the script can be run as root on the device? It would have access to copy anything it likes then.

**Comment by mjfwalsh** [comment]
So your latest issue is that when adb-sync gets a permissions error while trying to index a directory it quits. Running adb in root mode should solve this but it shouldn't really be necessary.

Since my last commit, adb-sync stops trying to index the contents of ignored folders so that should greatly reduce the number of files being indexed, and side step any permissions errors you get while trying to index them.

Btw, the command you're running should be:

    ./adb-sync -rcdmn --exclude-path Android /sdcard /run/media/dilligaf/Vault/PixelTest

Since the exclude path is relative to the /sdcard directory.

**Comment by dillongaf** [comment]
Awesome! That worked without an issue

Thanks for the help :)
